import express from "express";
import productsRoutes from "./product.route.js";
import usersRoutes from "./auth.route.js";
import brandsRoutes from "./brand.route.js";
import categoriesRoutes from "./category.route.js";
import ordersRoutes from "./order.route.js";
import addressesRoutes from "./address.route.js";
import uploadRoutes from "./upload.js";
import storeRoutes from "./store.route.js";
import reviewRoutes from "./review.route.js";
import chatRoutes from "./chat.route.js";
import notificationRoutes from "./notification.route.js";
import couponRoutes from "./coupon.route.js";
import brandRequestRoutes from "./brandRequest.route.js";
import categoryRequestRoutes from "./categoryRequest.route.js";
import returnRoutes from "./return.route.js";
import collectionRoutes from "./collection.route.js";
import bulkProductRoutes from "./bulkProduct.route.js";
import advertisementRoutes from "./advertisement.route.js";
import heroSlideRoutes from "./heroSlide.route.js";
import installationServiceRoutes from "./installationService.route.js";
import paymentRoutes from "./payment.route.js";
import quotationRoutes from "./quotation.route.js";
import homeFeedRoutes from "./home.route.js";
import questionRoutes from "./question.route.js";
import shippingRoutes from "./shipping.route.js";
import accurateRoutes from "./accurate.route.js";
import opsRoutes from "../modules/ops/routes.js";
import subscriberRoutes from "./subscriber.route.js";
import socialProofRoutes from "./socialProof.route.js";
import mosaicCardRoutes from "./mosaicCard.route.js";
import roleRoutes from "./role.route.js";
import emailPrefsRoutes from "./emailPreferences.route.js";
import payoutRoutes from "./payout.route.js";
import layoutRoutes from "./pageLayout.route.js";
import paymobChannelRoutes from "./paymobChannel.route.js";
import storefrontVisibilityRoutes from "./storefrontVisibility.route.js";
import stockAlertRoutes from "./stockAlert.route.js";
import dataResetRoutes from "./dataReset.route.js";
import studentProgramRoutes from "./studentProgram.route.js";
import supportAssistantRoutes from "./supportAssistant.route.js";
import contactRoutes from "./contact.route.js";
import socialRoutes from "./social.route.js";

const router = express.Router();

router.use("/home-feed", homeFeedRoutes);
router.use("/products", productsRoutes);
router.use("/users", usersRoutes);
router.use("/brands", brandsRoutes);
router.use("/categories", categoriesRoutes);
router.use("/addresses", addressesRoutes);
router.use("/orders", ordersRoutes);
router.use("/upload", uploadRoutes);
router.use("/stores", storeRoutes);
router.use("/reviews", reviewRoutes);
router.use("/chat", chatRoutes);
router.use("/support", supportAssistantRoutes);
router.use("/social", socialRoutes);
router.use("/contact", contactRoutes);
router.use("/notifications", notificationRoutes);
router.use("/coupons", couponRoutes);
router.use("/brand-requests", brandRequestRoutes);
router.use("/category-requests", categoryRequestRoutes);
router.use("/returns", returnRoutes);
router.use("/collections", collectionRoutes);
router.use("/bulk-products", bulkProductRoutes);
router.use("/advertisements", advertisementRoutes);
router.use("/hero-slides", heroSlideRoutes);
router.use("/installation-services", installationServiceRoutes);
router.use("/payments", paymentRoutes);
router.use("/quotations", quotationRoutes);
router.use("/questions", questionRoutes);
router.use("/shipping", shippingRoutes);
router.use("/accurate", accurateRoutes);
router.use("/subscribers", subscriberRoutes);
router.use("/social-proof", socialProofRoutes);
router.use("/mosaic-cards", mosaicCardRoutes);
router.use("/roles", roleRoutes);
router.use("/emails", emailPrefsRoutes);
router.use("/payouts", payoutRoutes);
router.use("/layouts", layoutRoutes);
router.use("/paymob-channels", paymobChannelRoutes);
router.use("/storefront-visibility", storefrontVisibilityRoutes);
router.use("/stock-alerts", stockAlertRoutes);
router.use("/students", studentProgramRoutes);
router.use("/data-reset", dataResetRoutes);

// ops module owns: /analytics, /audit-logs, /site-mode, /cron
router.use("/", opsRoutes);

export default router;
