import express from "express";
import productsRoutes from "./product.route.js";
import usersRoutes from "./auth.route.js";
import brandsRoutes from "./brand.route.js";
import categoriesRoutes from "./category.route.js";
import ordersRoutes from "./order.route.js";
import addressesRoutes from "./address.route.js";
import uploadRoutes from "./upload.js";
import storeRoutes from "./store.route.js";
import analyticsRoutes from "./analytics.route.js";
import reviewRoutes from "./review.route.js";
import chatRoutes from "./chat.route.js";
import notificationRoutes from "./notification.route.js";
import couponRoutes from "./coupon.route.js";
import brandRequestRoutes from "./brandRequest.route.js";
import categoryRequestRoutes from "./categoryRequest.route.js";
import returnRoutes from "./return.route.js";
import collectionRoutes from "./collection.route.js";
import bulkProductRoutes from "./bulkProduct.route.js";
import advertisementRoutes from "./advertisement.route.js";
import paymentRoutes from "./payment.route.js";
import quotationRoutes from "./quotation.route.js";
import homeFeedRoutes from "./home.route.js";
import siteModeRoutes from "./siteMode.route.js";
import cronRoutes from "./cron.route.js";
import questionRoutes from "./question.route.js";
import shippingRoutes from "./shipping.route.js";
import accurateRoutes from "./accurate.route.js";
import auditLogRoutes from "./auditLog.route.js";

const router = express.Router();

router.use("/home-feed", homeFeedRoutes);
router.use("/products", productsRoutes);
router.use("/users", usersRoutes);
router.use("/brands", brandsRoutes);
router.use("/categories", categoriesRoutes);
router.use("/addresses", addressesRoutes);
router.use("/orders", ordersRoutes);
router.use("/upload", uploadRoutes);
router.use("/stores", storeRoutes);
router.use("/analytics", analyticsRoutes);
router.use("/reviews", reviewRoutes);
router.use("/chat", chatRoutes);
router.use("/notifications", notificationRoutes);
router.use("/coupons", couponRoutes);
router.use("/brand-requests", brandRequestRoutes);
router.use("/category-requests", categoryRequestRoutes);
router.use("/returns", returnRoutes);
router.use("/collections", collectionRoutes);
router.use("/bulk-products", bulkProductRoutes);
router.use("/advertisements", advertisementRoutes);
router.use("/payments", paymentRoutes);
router.use("/quotations", quotationRoutes);
router.use("/site-mode", siteModeRoutes);
router.use("/cron", cronRoutes);
router.use("/questions", questionRoutes);
router.use("/shipping", shippingRoutes);
router.use("/accurate", accurateRoutes);
router.use("/audit-logs", auditLogRoutes);

export default router;
