import mongoose from "mongoose";

/**
 * StorePayout — one row per period of vendor remittance.
 *
 * Generated by an admin from delivered+paid orders in a date window. The
 * snapshot fields (commissionRate, grossSales, platformFee, netPayable)
 * freeze the numbers at creation time so later edits to Store.commission or
 * Order.itemsPrice don't change historical statements.
 *
 * shippingTotal is informational only — shipping fees go to the platform /
 * carrier, never to the vendor.
 */
const storePayoutSchema = new mongoose.Schema(
  {
    store: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Store",
      required: true,
      index: true,
    },
    periodStart: { type: Date, required: true },
    periodEnd: { type: Date, required: true },

    orderIds: [{ type: mongoose.Schema.Types.ObjectId, ref: "Order" }],
    ordersCount: { type: Number, default: 0, min: 0 },

    grossSales: { type: Number, required: true, min: 0 },
    shippingTotal: { type: Number, default: 0, min: 0 },
    commissionRate: { type: Number, required: true, min: 0, max: 100 },
    platformFee: { type: Number, required: true, min: 0 },
    netPayable: { type: Number, required: true, min: 0 },

    currency: { type: String, default: "EGP" },

    status: {
      type: String,
      enum: ["pending", "paid", "failed", "cancelled"],
      default: "pending",
      index: true,
    },

    method: {
      type: String,
      enum: ["bank_transfer", "instapay", "wallet", "manual", null],
      default: null,
    },
    reference: { type: String, trim: true },
    notes: { type: String, trim: true },

    createdBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
    paidAt: { type: Date },
    paidBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
  },
  { timestamps: true }
);

storePayoutSchema.index({ store: 1, periodStart: 1, periodEnd: 1 });
storePayoutSchema.index({ status: 1, createdAt: -1 });

const StorePayout = mongoose.model("StorePayout", storePayoutSchema);
export default StorePayout;
